// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD66uU3N-3p-r2gdnmKI4isOaoQscgtccY',
    appId: '1:755299339588:web:f67204f6ae8347d1e5db11',
    messagingSenderId: '755299339588',
    projectId: 'kidsgaurdian',
    authDomain: 'kidsgaurdian.firebaseapp.com',
    storageBucket: 'kidsgaurdian.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoA49VpAYah3GO6SUN_2gQUsxtiUUvSfk',
    appId: '1:755299339588:android:b7b5d7f0006786cde5db11',
    messagingSenderId: '755299339588',
    projectId: 'kidsgaurdian',
    storageBucket: 'kidsgaurdian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzhj32zvyd9JMZYoFrhMXrCl5Bn8yPsM',
    appId: '1:755299339588:ios:034c55b02a11a626e5db11',
    messagingSenderId: '755299339588',
    projectId: 'kidsgaurdian',
    storageBucket: 'kidsgaurdian.appspot.com',
    iosClientId: '755299339588-dgt3a76960r8mk8q36jdhs1nd9kblvhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.childapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTzhj32zvyd9JMZYoFrhMXrCl5Bn8yPsM',
    appId: '1:755299339588:ios:c1d68d7a966e8939e5db11',
    messagingSenderId: '755299339588',
    projectId: 'kidsgaurdian',
    storageBucket: 'kidsgaurdian.appspot.com',
    iosClientId: '755299339588-uraour7vaup4eeftoikgunmdvfqhsg81.apps.googleusercontent.com',
    iosBundleId: 'com.example.childapp.RunnerTests',
  );
}
